export default [
  { type: 'Button', label: 'Buton' },
  { type: 'Alert', label: 'Uyarı' },
  { type: 'Navbar', label: 'Navbar' },
  { type: 'Container', label: 'Container' },
  { type: 'Grid', label: 'Grid' },
  { type: 'Flex', label: 'Flex' },
  { type: 'Card', label: 'Kart' },
  { type: 'Modal', label: 'Modal' },
  { type: 'Badge', label: 'Badge' },
  { type: 'ListGroup', label: 'List Group' },
  { type: 'Progress', label: 'Progress' },
  { type: 'Spinner', label: 'Spinner' },
  { type: 'Toast', label: 'Toast' },
  { type: 'Tooltip', label: 'Tooltip' },
  { type: 'Popover', label: 'Popover' },
  { type: 'Collapse', label: 'Collapse' },
  { type: 'Dropdown', label: 'Dropdown' },
  { type: 'Pagination', label: 'Pagination' },
  { type: 'Breadcrumb', label: 'Breadcrumb' },
  { type: 'Accordion', label: 'Accordion' },
  { type: 'Carousel', label: 'Carousel' },
  { type: 'Offcanvas', label: 'Offcanvas' },
  { type: 'Nav', label: 'Nav' },
  { type: 'Tabs', label: 'Tabs' },
  { type: 'Form', label: 'Form' },
  { type: 'InputGroup', label: 'InputGroup' },
  { type: 'Table', label: 'Table' },
  { type: 'Image', label: 'Image' },
  { type: 'Close', label: 'Close' },
  { type: 'Placeholder', label: 'Placeholder' }
]
